collections:
  songs:
    output: true
    permalink: /xmusic/:name/
collections:
  playlists:
    output: true
    permalink: /playlists/:name/
collections:
  playlists:
    output: true
    permalink: /songs/:name/
